//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiDtControlSample.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiDtControlSample.Resources.Strings.MenuResources", typeof(MenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string ACCOUNT {
            get {
                return ResourceManager.GetString("ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Info.
        /// </summary>
        public static string ACCOUNT_TOOLTIP {
            get {
                return ResourceManager.GetString("ACCOUNT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string ACCOUNTDEPARTMENT {
            get {
                return ResourceManager.GetString("ACCOUNTDEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Dashboard.
        /// </summary>
        public static string ACCOUNTING_BUSINESS_DASHBOARD {
            get {
                return ResourceManager.GetString("ACCOUNTING_BUSINESS_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivable.
        /// </summary>
        public static string ACCOUNTING_CUSTOMER {
            get {
                return ResourceManager.GetString("ACCOUNTING_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Dashboard.
        /// </summary>
        public static string ACCOUNTING_HOURLY_DASHBOARD {
            get {
                return ResourceManager.GetString("ACCOUNTING_HOURLY_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable.
        /// </summary>
        public static string ACCOUNTING_VENDOR {
            get {
                return ResourceManager.GetString("ACCOUNTING_VENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string ACCOUNTINGMAINTENANCE {
            get {
                return ResourceManager.GetString("ACCOUNTINGMAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Reports.
        /// </summary>
        public static string ACCOUNTINGREPORTSGROUP {
            get {
                return ResourceManager.GetString("ACCOUNTINGREPORTSGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP/AR.
        /// </summary>
        public static string APARGROUP {
            get {
                return ResourceManager.GetString("APARGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Inquiry.
        /// </summary>
        public static string APINQUIRY {
            get {
                return ResourceManager.GetString("APINQUIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/R Customer Inquiry.
        /// </summary>
        public static string ARINQUIRY {
            get {
                return ResourceManager.GetString("ARINQUIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Deposits.
        /// </summary>
        public static string BANKDEPOSITS {
            get {
                return ResourceManager.GetString("BANKDEPOSITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bill.
        /// </summary>
        public static string BILL {
            get {
                return ResourceManager.GetString("BILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Payment.
        /// </summary>
        public static string BILLPAYMENT {
            get {
                return ResourceManager.GetString("BILLPAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Type Management.
        /// </summary>
        public static string BODYTYPEMANAGEMENT_LIST {
            get {
                return ResourceManager.GetString("BODYTYPEMANAGEMENT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Package.
        /// </summary>
        public static string BUNDLE_LIST {
            get {
                return ResourceManager.GetString("BUNDLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Major Unit Bundles, Add accessories or service to a unit.
        /// </summary>
        public static string BUNDLE_LIST_TOOLTIP {
            get {
                return ResourceManager.GetString("BUNDLE_LIST_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash and Bank.
        /// </summary>
        public static string CASHANDBANK {
            get {
                return ResourceManager.GetString("CASHANDBANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Close Cashier.
        /// </summary>
        public static string CASHIER_OPENCLOSE {
            get {
                return ResourceManager.GetString("CASHIER_OPENCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Payments.
        /// </summary>
        public static string CASHIER_RECEIVEPAYMENT {
            get {
                return ResourceManager.GetString("CASHIER_RECEIVEPAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier Management.
        /// </summary>
        public static string CASHIERMANAGEMENT {
            get {
                return ResourceManager.GetString("CASHIERMANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Detail.
        /// </summary>
        public static string CATEGORY_DETAIL {
            get {
                return ResourceManager.GetString("CATEGORY_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Dealership.
        /// </summary>
        public static string CHANGE_DEALERSHIP {
            get {
                return ResourceManager.GetString("CHANGE_DEALERSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of Accounts.
        /// </summary>
        public static string CHART_OF_ACCOUNTS {
            get {
                return ResourceManager.GetString("CHART_OF_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string CONSOLE {
            get {
                return ResourceManager.GetString("CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string CONTACT_LIST {
            get {
                return ResourceManager.GetString("CONTACT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Test Page.
        /// </summary>
        public static string CONTROL_TEST_PAGE {
            get {
                return ResourceManager.GetString("CONTROL_TEST_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Check.
        /// </summary>
        public static string CREATECHECK {
            get {
                return ResourceManager.GetString("CREATECHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credit Card Credit.
        /// </summary>
        public static string CREDITCARDCREDIT {
            get {
                return ResourceManager.GetString("CREDITCARDCREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Credit Memo.
        /// </summary>
        public static string CREDITMEMO {
            get {
                return ResourceManager.GetString("CREDITMEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Editor.
        /// </summary>
        public static string CUSTOM_LABEL {
            get {
                return ResourceManager.GetString("CUSTOM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CUSTOMER_LIST {
            get {
                return ResourceManager.GetString("CUSTOMER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Leads.
        /// </summary>
        public static string DEAD_LEAD_LIST {
            get {
                return ResourceManager.GetString("DEAD_LEAD_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealership Setting.
        /// </summary>
        public static string DEALERSHIP_SETTING {
            get {
                return ResourceManager.GetString("DEALERSHIP_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealership Setup.
        /// </summary>
        public static string DEALERSHIP_SETUP_LIST {
            get {
                return ResourceManager.GetString("DEALERSHIP_SETUP_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string EMPLOYEE_LIST {
            get {
                return ResourceManager.GetString("EMPLOYEE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Estimate.
        /// </summary>
        public static string ESTIMATE {
            get {
                return ResourceManager.GetString("ESTIMATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Expense.
        /// </summary>
        public static string EXPENSE {
            get {
                return ResourceManager.GetString("EXPENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Transactions.
        /// </summary>
        public static string EXPENSETRANSACTIONS {
            get {
                return ResourceManager.GetString("EXPENSETRANSACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F&amp;I.
        /// </summary>
        public static string FANDI_LIST {
            get {
                return ResourceManager.GetString("FANDI_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string FEE_LIST {
            get {
                return ResourceManager.GetString("FEE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        public static string GENERAL_LEDGER_GROUP {
            get {
                return ResourceManager.GetString("GENERAL_LEDGER_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        public static string GERNAL_LEDGER {
            get {
                return ResourceManager.GetString("GERNAL_LEDGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string GROUP_ACCOUNTING {
            get {
                return ResourceManager.GetString("GROUP_ACCOUNTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        public static string GROUP_CASHIER_FUNCTION {
            get {
                return ResourceManager.GetString("GROUP_CASHIER_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealerships.
        /// </summary>
        public static string GROUP_CHANGE_DEALERSHIP {
            get {
                return ResourceManager.GetString("GROUP_CHANGE_DEALERSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string GROUP_CUSTOMER {
            get {
                return ResourceManager.GetString("GROUP_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc..
        /// </summary>
        public static string GROUP_DLRSETTING {
            get {
                return ResourceManager.GetString("GROUP_DLRSETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Pad.
        /// </summary>
        public static string GROUP_LAUNCHPAD {
            get {
                return ResourceManager.GetString("GROUP_LAUNCHPAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Units.
        /// </summary>
        public static string GROUP_MAJORUNITS {
            get {
                return ResourceManager.GetString("GROUP_MAJORUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string GROUP_NAVIGATE_TO {
            get {
                return ResourceManager.GetString("GROUP_NAVIGATE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string GROUP_PARTS {
            get {
                return ResourceManager.GetString("GROUP_PARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts and Accessories .
        /// </summary>
        public static string GROUP_PARTS_TOOLTIP {
            get {
                return ResourceManager.GetString("GROUP_PARTS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string GROUP_SERVICE {
            get {
                return ResourceManager.GetString("GROUP_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string GROUP_SETTINGS {
            get {
                return ResourceManager.GetString("GROUP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string GROUP_SIGNOUT {
            get {
                return ResourceManager.GetString("GROUP_SIGNOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Pages.
        /// </summary>
        public static string GROUP_TESTING {
            get {
                return ResourceManager.GetString("GROUP_TESTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Clock.
        /// </summary>
        public static string GROUP_TIME {
            get {
                return ResourceManager.GetString("GROUP_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help and Support.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help and Support.
        /// </summary>
        public static string HELP_TOOLTIP {
            get {
                return ResourceManager.GetString("HELP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Parts Price File.
        /// </summary>
        public static string IMPORTPARTSPRICEFILE {
            get {
                return ResourceManager.GetString("IMPORTPARTSPRICEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Payroll JE&apos;s.
        /// </summary>
        public static string IMPORTPAYROLL {
            get {
                return ResourceManager.GetString("IMPORTPAYROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incentive.
        /// </summary>
        public static string INCENTIVE_LIST {
            get {
                return ResourceManager.GetString("INCENTIVE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage OEM Incentives New, Modify, Delete.
        /// </summary>
        public static string INCENTIVE_LIST_TOOLTIP {
            get {
                return ResourceManager.GetString("INCENTIVE_LIST_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Transfers.
        /// </summary>
        public static string INCOMING_REQUEEST_TRANSFER {
            get {
                return ResourceManager.GetString("INCOMING_REQUEEST_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate Transfer.
        /// </summary>
        public static string INITIATE_TRANSFER {
            get {
                return ResourceManager.GetString("INITIATE_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string INVENTORY_LIST {
            get {
                return ResourceManager.GetString("INVENTORY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving.
        /// </summary>
        public static string INVENTORYRECEIVING_LIST {
            get {
                return ResourceManager.GetString("INVENTORYRECEIVING_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Invoice.
        /// </summary>
        public static string INVOICE {
            get {
                return ResourceManager.GetString("INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string INVOICE_LIST {
            get {
                return ResourceManager.GetString("INVOICE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or Update Parts Invoices.
        /// </summary>
        public static string INVOICE_TOOLTIP {
            get {
                return ResourceManager.GetString("INVOICE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string ITEM_LIST {
            get {
                return ResourceManager.GetString("ITEM_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Job Template.
        /// </summary>
        public static string JOB_TEMPLATE_LIST {
            get {
                return ResourceManager.GetString("JOB_TEMPLATE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Entry.
        /// </summary>
        public static string JOURNAL_ENTRY {
            get {
                return ResourceManager.GetString("JOURNAL_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Printing.
        /// </summary>
        public static string LABEL_PRINTING {
            get {
                return ResourceManager.GetString("LABEL_PRINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Pad.
        /// </summary>
        public static string LAUNCHPAD {
            get {
                return ResourceManager.GetString("LAUNCHPAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads.
        /// </summary>
        public static string LEAD_LIST {
            get {
                return ResourceManager.GetString("LEAD_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads.
        /// </summary>
        public static string LEADS {
            get {
                return ResourceManager.GetString("LEADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Units.
        /// </summary>
        public static string MAJOR_UNITS {
            get {
                return ResourceManager.GetString("MAJOR_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Unit Invoicing.
        /// </summary>
        public static string MAJOR_UNITS_INVOICING {
            get {
                return ResourceManager.GetString("MAJOR_UNITS_INVOICING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new major unit invoice.
        /// </summary>
        public static string MAJOR_UNITS_INVOICING_TOOLTIP {
            get {
                return ResourceManager.GetString("MAJOR_UNITS_INVOICING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Units.
        /// </summary>
        public static string MAJOR_UNITS_TOOLTIP {
            get {
                return ResourceManager.GetString("MAJOR_UNITS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Management.
        /// </summary>
        public static string MAJORUNITMANAGEMENT_GROUP {
            get {
                return ResourceManager.GetString("MAJORUNITMANAGEMENT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Unit Management Menu.
        /// </summary>
        public static string MAJORUNITMANAGEMENT_GROUP_TOOLTIP {
            get {
                return ResourceManager.GetString("MAJORUNITMANAGEMENT_GROUP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Reports.
        /// </summary>
        public static string MAJORUNITREPORTS {
            get {
                return ResourceManager.GetString("MAJORUNITREPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Unit Reporting System.
        /// </summary>
        public static string MAJORUNITREPORTS_TOOLTIP {
            get {
                return ResourceManager.GetString("MAJORUNITREPORTS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Checks.
        /// </summary>
        public static string MANUAL_CHECKS {
            get {
                return ResourceManager.GetString("MANUAL_CHECKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual GL Posting.
        /// </summary>
        public static string MANUAL_GL_POSTING {
            get {
                return ResourceManager.GetString("MANUAL_GL_POSTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Update.
        /// </summary>
        public static string MASS_UPDATE {
            get {
                return ResourceManager.GetString("MASS_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string MISC_LIST {
            get {
                return ResourceManager.GetString("MISC_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Receipt / Paid Out.
        /// </summary>
        public static string MISC_RECEIPT_PAID_OUT {
            get {
                return ResourceManager.GetString("MISC_RECEIPT_PAID_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string MODEL_LIST {
            get {
                return ResourceManager.GetString("MODEL_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Management.
        /// </summary>
        public static string MODELMANAGEMENT_LIST {
            get {
                return ResourceManager.GetString("MODELMANAGEMENT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Management New, Modify, Delete.
        /// </summary>
        public static string MODELMANAGEMENT_LIST_TOOLTIP {
            get {
                return ResourceManager.GetString("MODELMANAGEMENT_LIST_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Category.
        /// </summary>
        public static string MU_CATEGORY_LIST {
            get {
                return ResourceManager.GetString("MU_CATEGORY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Management New, Modify, Delete.
        /// </summary>
        public static string MU_CATEGORY_LIST_TOOLTIP {
            get {
                return ResourceManager.GetString("MU_CATEGORY_LIST_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Invoice List.
        /// </summary>
        public static string MU_INVOICE_LIST {
            get {
                return ResourceManager.GetString("MU_INVOICE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Receive Transfer.
        /// </summary>
        public static string MU_RECEIVE_TRANSFER {
            get {
                return ResourceManager.GetString("MU_RECEIVE_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive a Major Unit Transfer from another dealership.
        /// </summary>
        public static string MU_RECEIVE_TRANSFER_TOOLTIP {
            get {
                return ResourceManager.GetString("MU_RECEIVE_TRANSFER_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Inventory.
        /// </summary>
        public static string MUINVENTORY_LIST {
            get {
                return ResourceManager.GetString("MUINVENTORY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Unit Inventory New, Modify, Delete.
        /// </summary>
        public static string MUINVENTORY_LIST_TOOLTIP {
            get {
                return ResourceManager.GetString("MUINVENTORY_LIST_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Receiving - USED.
        /// </summary>
        public static string MURECEIVINGUSEDUNIT {
            get {
                return ResourceManager.GetString("MURECEIVINGUSEDUNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Receiving w/o PO.
        /// </summary>
        public static string MURECEIVINGWITHOUTPO {
            get {
                return ResourceManager.GetString("MURECEIVINGWITHOUTPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Receiving - NEW.
        /// </summary>
        public static string MURECEIVINGWITHPO {
            get {
                return ResourceManager.GetString("MURECEIVINGWITHPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Units Receiving.
        /// </summary>
        public static string MURECEIVINGWITHPO_TOOLTIP {
            get {
                return ResourceManager.GetString("MURECEIVINGWITHPO_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Sales.
        /// </summary>
        public static string MUSALES_LIST {
            get {
                return ResourceManager.GetString("MUSALES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Major Units sales in process or completed.
        /// </summary>
        public static string MUSALES_LIST_TOOLTIP {
            get {
                return ResourceManager.GetString("MUSALES_LIST_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate To.
        /// </summary>
        public static string NAVIGATE_TO {
            get {
                return ResourceManager.GetString("NAVIGATE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F &amp; I Sales.
        /// </summary>
        public static string NEWFISALE {
            get {
                return ResourceManager.GetString("NEWFISALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance and Insurance Management New, Modify, Delete.
        /// </summary>
        public static string NEWFISALE_TOOLTIP {
            get {
                return ResourceManager.GetString("NEWFISALE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Stock Category.
        /// </summary>
        public static string NONSTOCKCATEGORY {
            get {
                return ResourceManager.GetString("NONSTOCKCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Stock Item.
        /// </summary>
        public static string NONSTOCKITEM {
            get {
                return ResourceManager.GetString("NONSTOCKITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU Ordering.
        /// </summary>
        public static string ORDERING {
            get {
                return ResourceManager.GetString("ORDERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering List.
        /// </summary>
        public static string ORDERING_LIST {
            get {
                return ResourceManager.GetString("ORDERING_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Units Ordering.
        /// </summary>
        public static string ORDERING_TOOLTIP {
            get {
                return ResourceManager.GetString("ORDERING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Setup.
        /// </summary>
        public static string ORGANIZATION_SETUP_DETAIL {
            get {
                return ResourceManager.GetString("ORGANIZATION_SETUP_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Setup.
        /// </summary>
        public static string ORGANIZATION_SETUP_LIST {
            get {
                return ResourceManager.GetString("ORGANIZATION_SETUP_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Slips.
        /// </summary>
        public static string PACKINGSLIPS {
            get {
                return ResourceManager.GetString("PACKINGSLIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Category.
        /// </summary>
        public static string PART_CATEGORY_LIST {
            get {
                return ResourceManager.GetString("PART_CATEGORY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Parts Categories New, Modify, Delete.
        /// </summary>
        public static string PART_CATEGORY_LIST_TOOLTIP {
            get {
                return ResourceManager.GetString("PART_CATEGORY_LIST_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Invoice List.
        /// </summary>
        public static string PART_INVOICE_LIST {
            get {
                return ResourceManager.GetString("PART_INVOICE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Parts Invoices in progress or completed.
        /// </summary>
        public static string PART_INVOICE_LIST_TOOLTIP {
            get {
                return ResourceManager.GetString("PART_INVOICE_LIST_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Package.
        /// </summary>
        public static string PART_PACKAGE {
            get {
                return ResourceManager.GetString("PART_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Transfer.
        /// </summary>
        public static string PART_TRANSFER_IN {
            get {
                return ResourceManager.GetString("PART_TRANSFER_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Parts IN from another dealership.
        /// </summary>
        public static string PART_TRANSFER_IN_TOOLTIP {
            get {
                return ResourceManager.GetString("PART_TRANSFER_IN_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Dashboard.
        /// </summary>
        public static string PARTS_INVENTORY_DASHBOARD {
            get {
                return ResourceManager.GetString("PARTS_INVENTORY_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Dashboard.
        /// </summary>
        public static string PARTS_SALES_DASHBOARD {
            get {
                return ResourceManager.GetString("PARTS_SALES_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Inventory.
        /// </summary>
        public static string PARTSINVENTORY_LIST {
            get {
                return ResourceManager.GetString("PARTSINVENTORY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Inventory Management New, Modify, Delete.
        /// </summary>
        public static string PARTSINVENTORY_LIST_TOOLTIP {
            get {
                return ResourceManager.GetString("PARTSINVENTORY_LIST_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Management.
        /// </summary>
        public static string PARTSMANAGEMENT_GROUP {
            get {
                return ResourceManager.GetString("PARTSMANAGEMENT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Management sub menu.
        /// </summary>
        public static string PARTSMANAGEMENT_GROUP_TOOLTIP {
            get {
                return ResourceManager.GetString("PARTSMANAGEMENT_GROUP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Ordering.
        /// </summary>
        public static string PARTSORDERING {
            get {
                return ResourceManager.GetString("PARTSORDERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering screen for parts and accessories.
        /// </summary>
        public static string PARTSORDERING_TOOLTIP {
            get {
                return ResourceManager.GetString("PARTSORDERING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Receiving.
        /// </summary>
        public static string PARTSRECEIVING {
            get {
                return ResourceManager.GetString("PARTSRECEIVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive parts and accessories from ordering.
        /// </summary>
        public static string PARTSRECEIVING_TOOLTIP {
            get {
                return ResourceManager.GetString("PARTSRECEIVING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Reports.
        /// </summary>
        public static string PARTSREPORTS {
            get {
                return ResourceManager.GetString("PARTSREPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Reporting System.
        /// </summary>
        public static string PARTSREPORTS_TOOLTIP {
            get {
                return ResourceManager.GetString("PARTSREPORTS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Sales.
        /// </summary>
        public static string PARTSSALES_LIST {
            get {
                return ResourceManager.GetString("PARTSSALES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Return.
        /// </summary>
        public static string PARTSVENDORRETURN {
            get {
                return ResourceManager.GetString("PARTSVENDORRETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return parts to the vendor for credit.
        /// </summary>
        public static string PARTSVENDORRETURN_TOOLTIP {
            get {
                return ResourceManager.GetString("PARTSVENDORRETURN_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Bills.
        /// </summary>
        public static string PAYBILLS {
            get {
                return ResourceManager.GetString("PAYBILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string PAYMENTMETHOD_LIST {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Inventory.
        /// </summary>
        public static string PHYSICALINVENTORY {
            get {
                return ResourceManager.GetString("PHYSICALINVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take physical inventory of your dealership stock.
        /// </summary>
        public static string PHYSICALINVENTORY_TOOLTIP {
            get {
                return ResourceManager.GetString("PHYSICALINVENTORY_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Vehicle Sales.
        /// </summary>
        public static string POST_VEHICLE_SALES {
            get {
                return ResourceManager.GetString("POST_VEHICLE_SALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price File Upload.
        /// </summary>
        public static string PRICEFILEUPLOAD {
            get {
                return ResourceManager.GetString("PRICEFILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Checks.
        /// </summary>
        public static string PRINTCHECKS {
            get {
                return ResourceManager.GetString("PRINTCHECKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Margin Rule.
        /// </summary>
        public static string PROFITMARGIN {
            get {
                return ResourceManager.GetString("PROFITMARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Margin management, Rounders and Esclators.
        /// </summary>
        public static string PROFITMARGIN_TOOLTIP {
            get {
                return ResourceManager.GetString("PROFITMARGIN_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Bill.
        /// </summary>
        public static string QUICKBILL {
            get {
                return ResourceManager.GetString("QUICKBILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Payments.
        /// </summary>
        public static string RECEIVEPAYMENT {
            get {
                return ResourceManager.GetString("RECEIVEPAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconcile.
        /// </summary>
        public static string RECONCILECHECKINGACCOUNTS {
            get {
                return ResourceManager.GetString("RECONCILECHECKINGACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Transaction.
        /// </summary>
        public static string RECURRINGTRANSACTION {
            get {
                return ResourceManager.GetString("RECURRINGTRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Refund Receipt.
        /// </summary>
        public static string REFUNDRECEIPT {
            get {
                return ResourceManager.GetString("REFUNDRECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sales Receipt.
        /// </summary>
        public static string SALESRECEIPT {
            get {
                return ResourceManager.GetString("SALESRECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Scheduled Account.
        /// </summary>
        public static string SCHEDULE_ACCOUNT {
            get {
                return ResourceManager.GetString("SCHEDULE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Reconciliation.
        /// </summary>
        public static string SCHEDULE_RECONCILIATION {
            get {
                return ResourceManager.GetString("SCHEDULE_RECONCILIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string SCHEDULES {
            get {
                return ResourceManager.GetString("SCHEDULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        public static string SCHEDULING {
            get {
                return ResourceManager.GetString("SCHEDULING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Transactions.
        /// </summary>
        public static string SEARCH_TRANSACTIONS {
            get {
                return ResourceManager.GetString("SEARCH_TRANSACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal Ordering.
        /// </summary>
        public static string SEASONAL_ORDERING {
            get {
                return ResourceManager.GetString("SEASONAL_ORDERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or Modify Seasonal Ordering of parts and accessories.
        /// </summary>
        public static string SEASONAL_ORDERING_TOOLTIP {
            get {
                return ResourceManager.GetString("SEASONAL_ORDERING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Invoice List.
        /// </summary>
        public static string SERVICE_INVOICE_LIST {
            get {
                return ResourceManager.GetString("SERVICE_INVOICE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Dashboard.
        /// </summary>
        public static string SERVICE_SALES_DASHBOARD {
            get {
                return ResourceManager.GetString("SERVICE_SALES_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Dashboard.
        /// </summary>
        public static string SERVICE_STATIC_DASHBOARD {
            get {
                return ResourceManager.GetString("SERVICE_STATIC_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Management.
        /// </summary>
        public static string SERVICEMANAGEMENT_GROUP {
            get {
                return ResourceManager.GetString("SERVICEMANAGEMENT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Labor.
        /// </summary>
        public static string SERVICERATE {
            get {
                return ResourceManager.GetString("SERVICERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Reports.
        /// </summary>
        public static string SERVICEREPORTS {
            get {
                return ResourceManager.GetString("SERVICEREPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Sales.
        /// </summary>
        public static string SERVICERO_LIST {
            get {
                return ResourceManager.GetString("SERVICERO_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Sublet.
        /// </summary>
        public static string SERVICESUBLET {
            get {
                return ResourceManager.GetString("SERVICESUBLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string SIGNOUT {
            get {
                return ResourceManager.GetString("SIGNOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements.
        /// </summary>
        public static string STATEMENTS {
            get {
                return ResourceManager.GetString("STATEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string SUPPLIER_LIST {
            get {
                return ResourceManager.GetString("SUPPLIER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rates.
        /// </summary>
        public static string TAXRATES {
            get {
                return ResourceManager.GetString("TAXRATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Rates.
        /// </summary>
        public static string TECHNICIANRATE {
            get {
                return ResourceManager.GetString("TECHNICIANRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Time Clock.
        /// </summary>
        public static string TECHNICIANTIMECLOCK {
            get {
                return ResourceManager.GetString("TECHNICIANTIMECLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string TERM_LIST {
            get {
                return ResourceManager.GetString("TERM_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test DataGrid.
        /// </summary>
        public static string TEST_DATAGRID {
            get {
                return ResourceManager.GetString("TEST_DATAGRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test WebView.
        /// </summary>
        public static string TEST_WEBVIEW {
            get {
                return ResourceManager.GetString("TEST_WEBVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Clock.
        /// </summary>
        public static string TIMECLOCK {
            get {
                return ResourceManager.GetString("TIMECLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Clock Management.
        /// </summary>
        public static string TIMECLOCKMANAGEMENT {
            get {
                return ResourceManager.GetString("TIMECLOCKMANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Into Inventory.
        /// </summary>
        public static string TRANSFERINTOINVENTORY {
            get {
                return ResourceManager.GetString("TRANSFERINTOINVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Out of Inventory.
        /// </summary>
        public static string TRANSFEROUTOFINVENTORY {
            get {
                return ResourceManager.GetString("TRANSFEROUTOFINVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Parts OUT to another dealership.
        /// </summary>
        public static string TRANSFEROUTOFINVENTORY_TOOLTIP {
            get {
                return ResourceManager.GetString("TRANSFEROUTOFINVENTORY_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string TRANSFERS {
            get {
                return ResourceManager.GetString("TRANSFERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string VENDOR_LIST {
            get {
                return ResourceManager.GetString("VENDOR_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vendor Credit.
        /// </summary>
        public static string VENDORCREDIT {
            get {
                return ResourceManager.GetString("VENDORCREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Check Registers.
        /// </summary>
        public static string VIEWCHECKREGISTER {
            get {
                return ResourceManager.GetString("VIEWCHECKREGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Processing.
        /// </summary>
        public static string WARRANTY_PROCESSING {
            get {
                return ResourceManager.GetString("WARRANTY_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Order Import.
        /// </summary>
        public static string WEBSITEORDERINPORT {
            get {
                return ResourceManager.GetString("WEBSITEORDERINPORT", resourceCulture);
            }
        }
    }
}
